name: Publish new version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: 'patch'
        options:
          - 'major'
          - 'minor'
          - 'patch'
          - 'premajor'
          - 'preminor'
          - 'prepatch'
      preid:
        description: 'Prerelease identifier'
        required: false
        options:
          - 'alpha'
          - 'beta'
          - 'rc'

permissions:
  contents: write
  packages: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g @lerna-lite/cli @lerna-lite/version @lerna-lite/publish
      - name: Build packages
        run: npm run build

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Update version, no --preid
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event.inputs.preid == '' }}
        run: |
          # Update version in lerna.json
          lerna version ${{ github.event.inputs.version }} --create-release github --yes
      - name: Update version, with --preid
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event.inputs.preid != '' }}
        run: |
          # Update version in lerna.json
          lerna version ${{ github.event.inputs.version }} --preid ${{ github.event.inputs.preid }} --create-release github --yes
        

      - name: Publish packages
        run: |
          # Publish packages to npm
          lerna publish from-git
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
